### ISSUE TITLE
扩展程序设置Token和ID成功后信息消失

### ISSUE THREAD

**Issue by excelsior222** [lyh081/Book2Notion#1]
Hi Cetus~ @lyh081 

今天搜索到了你的这个扩展程序，从GitHub上下载了压缩包，解压之后成功安装进了Edge浏览器。

按照操作说明进行Token和ID的配置，出现了教程中所说的弹窗内容，Page里也有了一个名称为BookList的Database。

![微信截图_20220419001813](https://user-images.githubusercontent.com/93578207/163839470-8f3c881b-6a44-4aea-bc18-3d4477c4c107.png)

 但去图书页面保存的时候，弹窗报错，Database里也没有出现相关的数据。

![微信截图_20220419002028](https://user-images.githubusercontent.com/93578207/163839553-2d22e212-1e20-4d83-9156-72412c41faf7.png)

所以我又去扩展设置里看了一下，发现刚刚保存的信息已经消失了。测试了几遍，都是保存成功后，只要重新打开扩展设置，或者是刷新页面，Token和ID信息就会消失。

![微信截图_20220419002046](https://user-images.githubusercontent.com/93578207/163839768-3bf7a238-4543-4f7a-b020-103e90ba492a.png)

不知道是不是对Edge的兼容性问题TAT

**Comment by lyh081** [comment]
已经修复了这个问题了，现在Edge也可以使用啦

**Comment by excelsior222** [comment]
哇，可以了，感谢大佬~
